"""
Command Nexus License Key Generator
====================================
Standalone tool for Avery Logic Works to generate customer license keys.
NOT embedded in Command Nexus. Run this separately to create keys for customers.

Usage:
    python tools/license_key_generator.py --tier starter --days 30 --count 1
    python tools/license_key_generator.py --tier trial --days 15 --count 100
    python tools/license_key_generator.py --tier unlimited --days 30 --count 5

Output: Keys printed to console and optionally saved to a file.
"""

from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import secrets
import time
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path


class SubscriptionTier(Enum):
    TRIAL = "trial"
    STARTER = "starter"
    PRO = "pro"
    BUSINESS = "business"
    UNLIMITED = "unlimited"


# NOTE: This MUST match the secret in src/core/license_manager.py
_SECRET_KEY = b"AVERY_LOGIC_WORKS_COMMAND_NEXUS_2026"

_TIER_CODES = {
    SubscriptionTier.TRIAL: "TR",
    SubscriptionTier.STARTER: "ST",
    SubscriptionTier.PRO: "PR",
    SubscriptionTier.BUSINESS: "BU",
    SubscriptionTier.UNLIMITED: "UN",
}


def _normalize_key(key: str) -> str:
    return "".join(ch for ch in (key or "").strip().upper() if ch.isalnum())


def _format_key(raw: str) -> str:
    return "-".join(raw[i:i + 4] for i in range(0, len(raw), 4))


def generate_key(tier: SubscriptionTier, days_valid: int) -> str:
    """
    Generate a single license key.
    Format: TIER_CODE(2) + EXPIRY_HEX(10) + RANDOM(8) + HMAC(16) = 36 chars.
    Display format is 9 groups of 4 chars, separated by 8 dashes.
    """
    tier_code = _TIER_CODES[tier]

    expiry_ts = int(time.time()) + (days_valid * 86400)
    expiry_hex = f"{expiry_ts:010x}".upper()
    random_part = secrets.token_hex(4).upper()

    payload = f"{tier_code}{expiry_hex}{random_part}"
    hmac_digest = hmac.new(
        _SECRET_KEY,
        payload.encode(),
        hashlib.sha256,
    ).hexdigest()[:16].upper()

    raw = f"{tier_code}{expiry_hex}{random_part}{hmac_digest}"
    return _format_key(raw)


def validate_generated_key(key: str) -> tuple[bool, str, datetime]:
    """
    Validate a key that was generated by this tool.
    Returns (is_valid, tier_name, expiry_date).
    """
    key = _normalize_key(key)
    if len(key) != 36:
        return False, "invalid_length", datetime.now()

    tier_code = key[:2]
    expiry_hex = key[2:12]
    random_part = key[12:20]
    hmac_part = key[20:36]

    tier_map = {v: k for k, v in _TIER_CODES.items()}
    tier = tier_map.get(tier_code)
    if tier is None:
        return False, "unknown_tier", datetime.now()

    payload = f"{tier_code}{expiry_hex}{random_part}"
    expected_hmac = hmac.new(
        _SECRET_KEY,
        payload.encode(),
        hashlib.sha256,
    ).hexdigest()[:16].upper()

    if not hmac.compare_digest(hmac_part, expected_hmac):
        return False, "invalid_hmac", datetime.now()

    try:
        expiry_ts = int(expiry_hex, 16)
        expiry_date = datetime.fromtimestamp(expiry_ts)
    except (ValueError, OSError):
        return False, "bad_expiry", datetime.now()

    return True, tier.value, expiry_date


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Command Nexus license keys for customers."
    )
    parser.add_argument(
        "--tier",
        choices=[tier.value for tier in SubscriptionTier],
        help="Subscription tier for the generated key(s).",
    )
    parser.add_argument(
        "--days",
        type=int,
        default=30,
        help="Number of days the key is valid for. Default: 30.",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=1,
        help="Number of keys to generate. Default: 1.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Optional: Save generated keys to this file path.",
    )
    parser.add_argument(
        "--verify",
        type=str,
        default=None,
        help="Verify an existing key instead of generating.",
    )

    args = parser.parse_args()

    if args.verify:
        valid, tier_name, expiry = validate_generated_key(args.verify)
        if valid:
            print("\n✓ VALID KEY")
            print(f"  Tier:   {tier_name.upper()}")
            print(f"  Expiry: {expiry.strftime('%Y-%m-%d %H:%M:%S')}")
            days_left = (expiry - datetime.now()).days
            print(f"  Days left: {max(0, days_left)}")
        else:
            print(f"\n✗ INVALID KEY ({tier_name})")
        return

    if not args.tier:
        parser.error("--tier is required unless --verify is used")

    tier = SubscriptionTier(args.tier)
    days = 15 if tier == SubscriptionTier.TRIAL else args.days
    expiry_date = datetime.now() + timedelta(days=days)

    print("=" * 60)
    print("  COMMAND NEXUS LICENSE KEY GENERATOR")
    print("  Avery Logic Works")
    print("=" * 60)
    print(f"  Tier:     {tier.value.upper()}")
    print(f"  Duration: {days} days")
    print(f"  Expires:  {expiry_date.strftime('%Y-%m-%d')}")
    print(f"  Count:    {args.count}")
    print("=" * 60)
    print()

    keys = []
    for i in range(args.count):
        key = generate_key(tier, days)
        raw_key = _normalize_key(key)
        keys.append({
            "key": key,
            "raw_key": raw_key,
            "tier": tier.value,
            "days_valid": days,
            "expires": expiry_date.isoformat(),
            "generated_at": datetime.now().isoformat(),
        })
        print(f"  {i + 1}. {key}")

    print()
    print("=" * 60)
    print(f"  Generated {args.count} key(s) for {tier.value.upper()}")
    print("=" * 60)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(keys, f, indent=2)
        print(f"\n  Saved to: {output_path.resolve()}")

    batch_dir = Path(__file__).parent / "generated_keys"
    batch_dir.mkdir(exist_ok=True)
    batch_file = batch_dir / f"{tier.value}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(batch_file, "w", encoding="utf-8") as f:
        json.dump(keys, f, indent=2)
    print(f"  Batch record: {batch_file.resolve()}")

    print()
    print("  IMPORTANT: Keep these keys secure. Each key is single-use.")
    print("  Distribute to customers via your preferred secure channel.")
    print("=" * 60)


if __name__ == "__main__":
    main()
