"""
Command Nexus License Key Generator
====================================
Standalone tool for Pantheon Forge / Chad Harris to generate license keys.
NOT embedded in Command Nexus. Run this separately to create keys for customers.

Usage:
    python tools/license_key_generator.py --tier starter --days 30 --count 1
    python tools/license_key_generator.py --tier trial --days 15 --count 100
    python tools/license_key_generator.py --tier unlimited --days 30 --count 5

Output: Keys printed to console and optionally saved to a file.
"""

import argparse
import hashlib
import hmac
import json
import secrets
import sys
import time
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path


class SubscriptionTier(Enum):
    TRIAL = "trial"
    STARTER = "starter"
    PRO = "pro"
    ANNUAL = "annual"
    UNLIMITED = "unlimited"


# NOTE: This MUST match the secret in src/core/license_manager.py
_SECRET_KEY = b"PANTHEON_FORGE_COMMAND_NEXUS_2026"

_TIER_CODES = {
    SubscriptionTier.TRIAL: "TR",
    SubscriptionTier.STARTER: "ST",
    SubscriptionTier.PRO: "PR",
    SubscriptionTier.ANNUAL: "AN",
    SubscriptionTier.UNLIMITED: "UN",
}


def generate_key(tier: SubscriptionTier, days_valid: int) -> str:
    """
    Generate a single license key.
    Format: TIER_CODE(2) + EXPIRY_HEX(10) + RANDOM(8) + HMAC(20) = 40 chars
    """
    tier_code = _TIER_CODES[tier]

    # Expiry: current time + days, as hex timestamp
    expiry_ts = int(time.time()) + (days_valid * 86400)
    expiry_hex = f"{expiry_ts:010x}".upper()

    # Randomness to prevent key collision/prediction
    random_part = secrets.token_hex(4).upper()

    # HMAC-SHA256 of payload, truncated to 20 hex chars
    payload = f"{tier_code}{expiry_hex}{random_part}"
    hmac_digest = hmac.new(
        _SECRET_KEY,
        payload.encode(),
        hashlib.sha256
    ).hexdigest()[:20].upper()

    # Final key: add dashes for readability (XXXX-XXXX-XXXX-XXXX-XXXX)
    raw = f"{tier_code}{expiry_hex}{random_part}{hmac_digest}"
    formatted = "-".join(raw[i:i+4] for i in range(0, 40, 4))
    return formatted


def validate_generated_key(key: str) -> tuple[bool, str, datetime]:
    """
    Validate a key that was generated by this tool.
    Returns (is_valid, tier_name, expiry_date).
    """
    key = key.strip().upper().replace("-", "")
    if len(key) != 40:
        return False, "invalid", datetime.now()

    tier_code = key[:2]
    expiry_hex = key[2:12]
    random_part = key[12:20]
    hmac_part = key[20:40]

    tier_map = {v: k for k, v in _TIER_CODES.items()}
    tier = tier_map.get(tier_code)
    if tier is None:
        return False, "unknown", datetime.now()

    payload = f"{tier_code}{expiry_hex}{random_part}"
    expected_hmac = hmac.new(
        _SECRET_KEY,
        payload.encode(),
        hashlib.sha256
    ).hexdigest()[:20].upper()

    if not hmac.compare_digest(hmac_part, expected_hmac):
        return False, "invalid_hmac", datetime.now()

    try:
        expiry_ts = int(expiry_hex, 16)
        expiry_date = datetime.fromtimestamp(expiry_ts)
    except ValueError:
        return False, "bad_expiry", datetime.now()

    return True, tier.value, expiry_date


def main():
    parser = argparse.ArgumentParser(
        description="Generate Command Nexus license keys for customers."
    )
    parser.add_argument(
        "--tier",
        choices=["trial", "starter", "pro", "annual", "unlimited"],
        required=True,
        help="Subscription tier for the generated key(s)."
    )
    parser.add_argument(
        "--days",
        type=int,
        required=True,
        help="Number of days the key is valid for."
    )
    parser.add_argument(
        "--count",
        type=int,
        default=1,
        help="Number of keys to generate (default: 1)."
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Optional: Save generated keys to this file path."
    )
    parser.add_argument(
        "--verify",
        type=str,
        default=None,
        help="Verify an existing key instead of generating."
    )

    args = parser.parse_args()

    # ------------------------------------------------------------------
    # Verify mode
    # ------------------------------------------------------------------
    if args.verify:
        valid, tier_name, expiry = validate_generated_key(args.verify)
        if valid:
            print(f"\n✓ VALID KEY")
            print(f"  Tier:   {tier_name.upper()}")
            print(f"  Expiry: {expiry.strftime('%Y-%m-%d %H:%M:%S')}")
            days_left = (expiry - datetime.now()).days
            print(f"  Days left: {max(0, days_left)}")
        else:
            print(f"\n✗ INVALID KEY ({tier_name})")
        return

    # ------------------------------------------------------------------
    # Generation mode
    # ------------------------------------------------------------------
    tier = SubscriptionTier(args.tier)
    expiry_date = datetime.now() + timedelta(days=args.days)

    print("=" * 60)
    print("  COMMAND NEXUS LICENSE KEY GENERATOR")
    print("  Pantheon Forge / Chad Harris")
    print("=" * 60)
    print(f"  Tier:     {tier.value.upper()}")
    print(f"  Duration: {args.days} days")
    print(f"  Expires:  {expiry_date.strftime('%Y-%m-%d')}")
    print(f"  Count:    {args.count}")
    print("=" * 60)
    print()

    keys = []
    for i in range(args.count):
        key = generate_key(tier, args.days)
        keys.append({
            "key": key,
            "tier": tier.value,
            "days_valid": args.days,
            "expires": expiry_date.isoformat(),
            "generated_at": datetime.now().isoformat(),
        })
        print(f"  {i+1}. {key}")

    print()
    print("=" * 60)
    print(f"  Generated {args.count} key(s) for {tier.value.upper()}")
    print("=" * 60)

    # Save to file if requested
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(keys, f, indent=2)
        print(f"\n  Saved to: {output_path.resolve()}")

    # Also save to a default batch file for record-keeping
    batch_dir = Path(__file__).parent / "generated_keys"
    batch_dir.mkdir(exist_ok=True)
    batch_file = batch_dir / f"{tier.value}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(batch_file, "w", encoding="utf-8") as f:
        json.dump(keys, f, indent=2)
    print(f"  Batch record: {batch_file.resolve()}")

    print()
    print("  IMPORTANT: Keep these keys secure. Each key is single-use.")
    print("  Distribute to customers via your preferred secure channel.")
    print("=" * 60)


if __name__ == "__main__":
    main()
